### ISSUE TITLE
Error in recruit w/ single obs. in a stratum

### ISSUE THREAD

**Issue by tylermaule** [NUstat/generalizeR#12]
Hi @TimRuel  -- 

Question on an error I'm encountering -- when I'm running the following code, stratify() creates five strata, one of which has a single school/observation. Since calculating the variance of that school's covariates results in 0, the calculation of the mahalanobis distance fails and we get an (uncaught) error message.

Since there's only one possible obs. in the stratum, should we skip calculations for the strata and default to "recruiting" that school? I'll continue to think about the desired behavior in this case, but I wanted to reach out in case you had an easy answer.

Here's the code for reproducibility, along w/ a couple screenshots:

```
#library(generalizeR)
library(generalizeRdata)
library(tidyverse)
library(devtools)

load_all("./")

cc_df <- cc

inference_pop <- cc %>%
  filter(st == "AK") %>%
  filter(charter == 0) %>%
  filter(g_10_offered == "No")

#inference_pop <- read.csv("../zeroed_inf_pop.csv")

strat_output <- stratify(data = inference_pop,
                         guided = FALSE,
                         n_strata = 5,
                         variables = c("pct_white",
                                       "pct_male"),
                         idvar = "ncessch")

recruit_output <- recruit(strat_output,
                      guided = FALSE,
                      sample_size = 76
)
```

<img width="692" alt="Screen Shot 2022-09-13 at 08 54 26" src="https://user-images.githubusercontent.com/25360773/189920000-109983f8-4c19-4455-a607-1366fedfd4a0.png">

<img width="609" alt="Screen Shot 2022-09-13 at 08 55 29" src="https://user-images.githubusercontent.com/25360773/189920119-3fae3502-ba24-494e-9f74-a6d17c20afcc.png">

**Comment by TimRuel** [comment]
I think whoever wrote the initial code for recruit() considered the possibility that a stratum could have a single observation but didn't quite account for it correctly. More precisely, they put the following line of code in

`if (any(a == 0)) {a[which(a == 0)] <- 0.00000001 }`

where `a` is the list of variances of each variable in each stratum. It looks as though they were expecting these variances to be 0 in the event that a stratum had only a single observation but R actually returns an `NA` instead, hence the error. I've updated the code to the following

`if (anyNA(a) || any(a == 0)) {a[which(is.na(a) || a == 0)] <- 0.00000001}`

I'll double check with Beth to be sure, but I believe this is the solution she wants.

Thanks for pointing out this error!
