### ISSUE TITLE
print(stratify(...)) doesn't appear to run correctly—at least not in line w/ vignette

### ISSUE THREAD

**Issue by tylermaule** [NUstat/generalizeR#14]
Printing an `generalizer_stratify` object no longer yields the organized output shown in the vignette, and ends w/ warning  "Warning message: In names(gp) : reached elapsed time limit"

<img width="779" alt="Screen Shot 2022-09-20 at 16 02 06" src="https://user-images.githubusercontent.com/25360773/191363887-6967dbf4-09a5-48cc-86f6-7c0f824d03d1.png">

**Comment by NicoleNixon** [comment]
If you redownload, this issue should be resolved
