### ISSUE TITLE
Error when attempting to print kable of recruit object (recruit_object$recruitment_kable)

### ISSUE THREAD

**Issue by tylermaule** [NUstat/generalizeR#15]
Found in the vignette, screenshot below: 

<img width="806" alt="Screen Shot 2022-09-20 at 18 35 02" src="https://user-images.githubusercontent.com/25360773/191383003-5fd9e49d-0350-4b66-b55f-3074ad246138.png">

**Comment by NicoleNixon** [comment]
If you redownload, this issues should be resolved
